"""Remove username field from User model

Revision ID: c73eb26d576f
Revises: efaa4db08375
Create Date: 2025-08-26 22:10:20.965919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73eb26d576f'
down_revision = 'efaa4db08375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)

    # ### end Alembic commands ###
