"""Add Google OAuth fields to User model

Revision ID: efaa4db08375
Revises: d23e4c7acdcc
Create Date: 2025-08-26 18:02:45.282909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaa4db08375'
down_revision = 'd23e4c7acdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('google_picture', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('google_picture')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
